apiVersion: apps/v1
kind: Deployment
metadata:
  name: swkoo-frontend
  namespace: swkoo
  labels:
    app: swkoo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swkoo-frontend
  template:
    metadata:
      labels:
        app: swkoo-frontend
    spec:
      imagePullSecrets:
        - name: ocir-credentials
      containers:
        - name: frontend
          image: icn.ocir.io/tenancy/swkoo-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: PORT
              value: "3000"
            - name: NEXT_PUBLIC_API_BASE_URL
              value: https://swkoo.kr/api
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
