apiVersion: apps/v1
kind: Deployment
metadata:
  name: swkoo-backend
  namespace: swkoo
  labels:
    app: swkoo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swkoo-backend
  template:
    metadata:
      labels:
        app: swkoo-backend
    spec:
      imagePullSecrets:
        - name: ocir-credentials
      containers:
        - name: backend
          image: icn.ocir.io/tenancy/swkoo-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: PORT
              value: "3000"
          envFrom:
            - secretRef:
                name: swkoo-backend-env
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
