apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swkoo-backend-data
  namespace: swkoo
  labels:
    app: swkoo-backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
