apiVersion: v1
kind: LimitRange
metadata:
  name: user-sample-limits
  namespace: user-sample
spec:
  limits:
    - type: Container
      default:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 10m
        memory: 16Mi
