apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: swkoo
resources:
  - common/namespace.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/ingress.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
