import { Injectable, Logger } from '@nestjs/common';
import { PatchStrategy, setHeaderOptions, V1Secret } from '@kubernetes/client-node';

import { KubeClient } from '../kube/kube.client';
import { UsersRepository } from '../onboarding/users.repository';

const ANNOTATION_KEY = 'swkoo.kr/env-rolled-at';
const KEY_REGEX = /^[A-Z_][A-Z0-9_]*$/;

function getStatus(err: unknown): number | undefined {
  const e = err as {
    code?: number;
    statusCode?: number;
    status?: number;
    response?: { statusCode?: number; status?: number };
  };
  return e.code ?? e.statusCode ?? e.status ?? e.response?.statusCode ?? e.response?.status;
}

/**
 * Manages user-controlled env vars for a deployment. Backed by a k8s Secret
 * (`<appName>-env`) in the user-<login> namespace. setEnv replaces the whole
 * Secret atomically and then bumps the deployment's pod template annotation
 * to force a rollout.
 *
 * RBAC: relies on the per-namespace Role/RoleBinding generated by
 * templates.ts at register time. If a user registered before this feature
 * shipped, they need to re-deploy once to pick up the RBAC manifests;
 * otherwise calls will return 403.
 */
@Injectable()
export class EnvService {
  private readonly logger = new Logger(EnvService.name);

  constructor(
    private readonly kube: KubeClient,
    private readonly users: UsersRepository
  ) {}

  private ns(login: string): string {
    return `user-${login.toLowerCase()}`;
  }

  private secretName(appName: string): string {
    return `${appName}-env`;
  }

  async getEnv(login: string, appName: string): Promise<Record<string, string>> {
    if (!this.kube.available()) throw new Error('KUBE_NOT_AVAILABLE');
    try {
      const secret = await this.kube.core!.readNamespacedSecret({
        name: this.secretName(appName),
        namespace: this.ns(login),
      });
      const data = (secret.data ?? {}) as Record<string, string>;
      const decoded: Record<string, string> = {};
      for (const [k, v] of Object.entries(data)) {
        decoded[k] = Buffer.from(v, 'base64').toString('utf8');
      }
      return decoded;
    } catch (err) {
      if (getStatus(err) === 404) return {};
      throw err;
    }
  }

  async setEnv(login: string, appName: string, vars: Record<string, string>): Promise<void> {
    if (!this.kube.available()) throw new Error('KUBE_NOT_AVAILABLE');
    for (const key of Object.keys(vars)) {
      if (!KEY_REGEX.test(key)) {
        throw new Error(`INVALID_KEY:${key}`);
      }
    }

    const namespace = this.ns(login);
    const name = this.secretName(appName);
    const data: Record<string, string> = {};
    for (const [k, v] of Object.entries(vars)) {
      data[k] = Buffer.from(v, 'utf8').toString('base64');
    }
    const body: V1Secret = {
      apiVersion: 'v1',
      kind: 'Secret',
      metadata: {
        name,
        namespace,
        labels: {
          'swkoo.kr/app': appName,
          'app.kubernetes.io/managed-by': 'swkoo-deploy',
        },
      },
      type: 'Opaque',
      data,
    };

    try {
      await this.kube.core!.replaceNamespacedSecret({ name, namespace, body });
    } catch (err) {
      if (getStatus(err) === 404) {
        await this.kube.core!.createNamespacedSecret({ namespace, body });
      } else {
        throw err;
      }
    }

    await this.triggerRestart(login, appName);

    // Audit log records which keys were set; values intentionally omitted.
    this.users.audit({
      actor: login,
      action: 'ENV_UPDATE',
      target: `${login}/${appName}`,
      reason: null,
      metaJson: JSON.stringify({ keys: Object.keys(vars) }),
    });
  }

  private async triggerRestart(login: string, appName: string): Promise<void> {
    const namespace = this.ns(login);
    // Strategic-merge patch on just the pod template annotation. Doesn't
    // touch image, replicas, env — so it never fights with Image Updater
    // or ArgoCD. Requires only the `patch` verb (Role grants it; the older
    // replace-based code path needed `update`, which the Role didn't have).
    const patchBody = {
      spec: {
        template: {
          metadata: {
            annotations: {
              [ANNOTATION_KEY]: new Date().toISOString(),
            },
          },
        },
      },
    };
    try {
      await this.kube.apps!.patchNamespacedDeployment(
        { name: appName, namespace, body: patchBody },
        setHeaderOptions('Content-Type', PatchStrategy.StrategicMergePatch)
      );
    } catch (err) {
      if (getStatus(err) === 404) {
        this.logger.warn(
          `triggerRestart: no deployment ${appName} in ${namespace} (pre-register?)`
        );
        return;
      }
      throw err;
    }
  }
}
