apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-sample-quota
  namespace: user-sample
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
    requests.storage: "1Gi"
    pods: "3"
    persistentvolumeclaims: "1"
    services: "5"
