apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swkoo-portfolio
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.swkoo-backend: ""
    notifications.argoproj.io/subscribe.on-sync-failed.swkoo-backend: ""
    notifications.argoproj.io/subscribe.on-health-degraded.swkoo-backend: ""
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord: ""
    notifications.argoproj.io/subscribe.on-health-degraded.discord: ""
spec:
  project: default
  source:
    repoURL: https://github.com/sungwookoo/swkoo-kr.git
    targetRevision: main
    path: deploy/base
  destination:
    server: https://kubernetes.default.svc
    namespace: swkoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
