apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swkoo-portfolio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sungwookoo/swkoo-portfolio.git
    targetRevision: main
    path: deploy/base
  destination:
    server: https://kubernetes.default.svc
    namespace: swkoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
